### ISSUE TITLE
Not working in handsontable latest version

### ISSUE THREAD

**Issue by happyhero0** [handsontable/handsontable-ruleJS#30]
Dear developers, I found latest versions like 0.24 etc. can't support formula.
I have to use the very old version 0.14.
When dragging the cell right-bottom border to bottom, it can't set right value using formula.
I found in the hook beforeAutofillInsidePopulate, the iterators is empty object.
And if the column has a renderer, the formula feature doen't work ,why ?
Thank you. Handsontable is great, but the formula feature has many problem....

**Comment by motin** [comment]
@budnix @Berus It would be great to hear what the current situation with this issue is - is this plugin vaporware currently, awaiting a new set of champions to maintain and update it to work with the latest versions? Is there a better alternative plugin or way of achieving formula support in handsontable currently or will there be in the future?
I love formula support but can't currently upgrade handsontable 0.19 to 0.27 without deactivating it :/

**Comment by AMBudnik** [comment]
Hi @motin 
We are switching for handle formulas as a plugin to Handsontable, project: https://github.com/handsontable/formula-parser

**Comment by motin** [comment]
@AMBudnik Thanks for the info, I'll head over there and see to it that we use that instead! May I suggest that you put this information up on the readme of this project? Thanks again

**Comment by AMBudnik** [comment]
We are planning to add the information after the alpha version is released.
Currently there is not full set of information. The only public part of the code is the parser that I've shown you.

**Comment by motin** [comment]
Btw, I found that old formulas are still working as usual after upgrade to 0.27 for us.
